services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    volumes:
      - "./configs/otel-collector.yaml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - 13133:13133 # health_check extension
    depends_on:
      - jaeger
      - prometheus
  jaeger:
    image: jaegertracing/all-in-one:latest
    volumes:
      - "./configs/jaeger-ui.json:/etc/jaeger/jaeger-ui.json"
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
    ports:
      - "6831:6831/udp" # UDP port for Jaeger agent
      - "16686:16686" # Web UI
      - "14268:14268" # HTTP port for spans
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - "./configs/prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
      - "8888:8888"
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

networks:
  default:
    name: opentelemetry-flask
    driver: bridge