# /tmp/otel-collector-config.yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
  debug:
    verbosity: detailed
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:9090"

processors:
  batch:
extensions:
  health_check: {}
service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug,otlp]
      processors: [batch]
    metrics:
      receivers: [otlp]
      exporters: [debug,prometheus]
      processors: [batch]
    logs:
      receivers: [otlp]
      exporters: [debug]
      processors: [batch]
